/** @module contracts */

import BigNumber from 'bignumber.js';

/**
 * Copyright (c) 2019 Burst Apps Team
 */

export type MethodArgument = string | number | boolean;

/**
 * The argument object for [[generateMethodCall]]
 *
 * @param {string} methodHash The signed long hash for the method generated by BlockTalk compiler
 * @param {MethodArgument[]} methodArgs Optional argument list for the method. Currently up to three args are supported
 */
export interface GenerateMethodCallArgs {
    methodHash: string;
    methodArgs?: MethodArgument[];
}
