name: Build and Release Desktop App

on:
  push:
    tags:
      - desktop-[0-9]+.[0-9]+.[0-9]+*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        package_manager: [npm]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Prepare build environment
        run: |
          cd ./scripts
          npm ci
          cd ../lib
          npm ci
          cd ../web/angular-wallet
          npm ci

      # TODO: add the web version

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          package_root: "./desktop/wallet"
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/desktop-') }}
