name: Build and Release Desktop App

on:
  push:
    tags:
      - desktop-[0-9]+.[0-9]+.[0-9]+*

jobs:
  release-web:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version String
        id: get-version
        uses: actions/github-script@v3
        with:
          script: return context.ref.replace('refs/tags/desktop-','')
          result-encoding: string

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Prepare build environment
        run: |
          cd ./scripts
          npm ci
          cd ../web/angular-wallet
          npm ci

      - name: Build Angular Web App
        id: build-web
        run: |
          cd ./web/angular-wallet
          npm run build:web
          assetFile=web-phoenix-signum-wallet.${{steps.get-version.outputs.result}}.zip
          echo "Zipping into $assetFile"
          zip -r $assetFile ./dist
          echo "::set-output name=assetFile::$assetFile"

      - name: Upload Web App Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./web/angular-wallet/${{steps.build-web.outputs.assetFile}}
          tag: v${{ steps.get-version.outputs.result }}
          prerelease: true
          body: YAY! New release. To make this release available in Phoenix, change tag to _desktop-${{ steps.get-version.outputs.result }}_ and remove [prerelease] state

  release-electron:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        package_manager: [ npm ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '2.7'
      - name: Display Python version
        run: python --version

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Prepare build environment
        run: |
          cd ./scripts
          npm ci
          cd ../web/angular-wallet
          npm ci

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          package_root: "./desktop/wallet"
          github_token: ${{ secrets.github_token }}
          release: true
